### ISSUE TITLE
这个项目和同类型的mybatis-plus或者spring-data-jpa比有何优势？

### ISSUE THREAD

**Issue by Anyzm** [hope-for/GyJdbc#4]
这个项目和同类型的mybatis-plus或者spring-data-jpa比有何优势？

**Comment by SpringStudent** [comment]
每个框架都有自己的优势，如果用mybatis的话选择mybatis-plus能够提升开发效率，spring-data-jpa对于单表查询的支持非常好，如果你使用的是JdbcTemplate的话，肯定开发中更倾向于写SQL，一般涉及多表，它肯定是个不错的选择
