### ISSUE TITLE
 解决不识闲SQLInterceptor项目启动失败问题

### ISSUE THREAD

**Issue by imblowsnow** [hope-for/GyJdbc#7]
你好这边可以发布个新版本吗

**Comment by imblowsnow** [comment]
1.2.6.RELEASE

**Comment by SpringStudent** [comment]
晚上发，现在用的话你可以实现个空的SQLInterceptor，像这样就不会启动报错了
![image](https://user-images.githubusercontent.com/14833956/202629222-b277416e-86ab-4599-9e6c-33801ddecc36.png)

**Comment by imblowsnow** [comment]
> 晚上发，现在用的话你可以实现个空的SQLInterceptor，像这样就不会启动报错了 ![image](https://user-images.githubusercontent.com/14833956/202629222-b277416e-86ab-4599-9e6c-33801ddecc36.png)

好的感谢，这边打算用在公司项目上

**Comment by SpringStudent** [comment]
嗯嗯，有bug可以及时反馈的，一直在维护的

**Comment by SpringStudent** [comment]
> 1.2.6.RELEASE

到时候用版本1.2.7.RELEASE哈

**Comment by SpringStudent** [comment]
> > 晚上发，现在用的话你可以实现个空的SQLInterceptor，像这样就不会启动报错了 ![image](https://user-images.githubusercontent.com/14833956/202629222-b277416e-86ab-4599-9e6c-33801ddecc36.png)
> 
> 好的感谢，这边打算用在公司项目上

大佬有在用了吗
